### ISSUE TITLE
Need a way to "freeze" tables to disk and reload them

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/agate#171]
For splitting up processing into chunks

Maybe a gzipped JSON format?

**Comment by ryanpitts** [comment]
You probably have seen this, @ftzeng does freezing in Broca: https://github.com/ftzeng/broca#freezing-pipes

https://github.com/ftzeng/broca/blob/master/broca/pipeline/cryo.py

**Comment by onyxfish** [comment]
Crazy rowing idea: can this be implemented as a memoizer that hashes the contents of the code inside a function. If the hashed code hasn't changed, load state from disk.

Would state need to be global for this to work?

**Comment by onyxfish** [comment]
Better idea: implement a class within journalism that the user registers "stages" with. (In an ordered list.) The class serialized the AST of each stage and if it hasn't changed from what's on disk loads that version. Huge advantage of this method: the forward cascade is trivial.

What about branching analysis? Is it possible to make these nest? Would it need to be a singleton? Would we need to maintain all state on the class itself?

**Comment by onyxfish** [comment]
Tree, not a list. Then the analysis can branch.

**Comment by onyxfish** [comment]
In this model it would be theoretically possible for a stage to have multiple antecedents. By starting analysis on multiple branches and then having them intersect further down the tree one could trivially parallelize dependent processing stages.

**Comment by onyxfish** [comment]
And of course you could also just parallelize non-intersecting branches...

**Comment by ftzeng** [comment]
Yes so if you look at how it is implemented in broca, this is what I'm
doing - you can use python's inspect module for this.

https://github.com/ftzeng/broca/blob/master/broca/pipeline/cryo.py

I'm not inspecting the source recursively, though I think it is possible,
though you would probably want to stop at a specific depth.

Crazy rowing idea: can this be implemented as a memoizer that hashes the
contents of the code inside a function. If the hashed code hasn't changed,
load state from disk.

Would state need to be global for this to work?

—
Reply to this email directly or view it on GitHub
<https://github.com/onyxfish/journalism/issues/171#issuecomment-135600756>.

**Comment by onyxfish** [comment]
@ftzeng Awesome, I haven't had a chance to look at broca's implementation yet but after I talked to Ryan about it I'm not surprised we converged on the same idea.

The only problem is now this is the feature I'm excited to implement but I have a bunch of other stuff I ought to do first. ;)

**Comment by onyxfish** [comment]
@ftzeng Knocked out a version of this today. If you have feedback I'd love to hear it:

Implementation: https://github.com/onyxfish/agate/blob/master/agate/analysis.py
Example: https://github.com/onyxfish/agate/blob/master/exonerations.py

**Comment by ftzeng** [comment]
Fantastic, your code is really neat. The bzipping is a great idea that I may borrow :)

**Comment by onyxfish** [comment]
@ftzeng Thanks! Glad you like it. One limitation of this approach is I end up caching the same tables over and over, which is why I need to compress the output. Bzipping can be slow, but I think its necessary to keep the file sizes manageable and I'm hoping the performance hit is offset by it not needing to run very often.

Ideally I'd like to figure out a way to cache only the delta of the "state", but that's very tricky without putting the burden of flagging what's changed on the user.
