### ISSUE TITLE
The API docs are missing/blank

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/agate#328]
Ugh. http://agate.readthedocs.org/en/1.0.0/api/aggregations.html

**Comment by onyxfish** [comment]
Not a bug, just not supported. Need a post-commit hook? https://github.com/rtfd/readthedocs.org/issues/1139

**Comment by kumarSC** [comment]
Hi @onyxfish , I am a mobile developer and a starter on open source projects. I want to contribute to open source starting with small things as I learn.I found this issue on github with tag documentation.Could you please suggest how I can get started on this issue?

**Comment by onyxfish** [comment]
Hey @kumarSC, thanks for your interest, unfortunately this particular issue is more of a process problem. It has to do with the specific limitations of the service that hosts the docs. As a result, I'm the only one who can really test it.

If you're interested in other suggestions, #307 would be a good small ticket, or if, your statistically inclined, any of the tickets that are open on [agate-stats](https://github.com/onyxfish/agate-stats/issues).

**Comment by onyxfish** [comment]
@kumarSC I just read more closely and realized you were specifically looking for documentation tickets. I'm afraid I'm mostly out of those. (I just did a major release.)

**Comment by onyxfish** [comment]
This was actually due to import errors. Fixed by specifying requirements-py2.txt in RTD config.
