### ISSUE TITLE
Setup Travis.ci

### ISSUE THREAD

**Issue by hunterowens** [onyxfish/agate#334]
Possible to setup Travis.ci or some other automated test server?

**Comment by onyxfish** [comment]
Sure, I've got it as part of my local build process, so I haven't bothered with it, but I know others prefer it so I can set that up.

**Comment by hunterowens** [comment]
Cool. Having the green travis passing button always gives people confidence. 

Also, allows you to continually test across pythons+oses, although your local setup might do that already.

**Comment by onyxfish** [comment]
Okay it's up and the build is passing. Just need to badge the docs. (This might also be the time to finally move away from a plain-text README.)
