### ISSUE TITLE
Bugs affecting joins with multiple matchs in right-hand table

### ISSUE THREAD

**Issue by kjam** [onyxfish/agate#336]
I'm having an issue migrating some of my journalism code. Attached you'll find two datasets as well as some Python to test the use case.

Here is the error I am receiving:

```python
/home/katharine/.virtualenv/book/local/lib/python2.7/site-packages/agate/table.pyc in join(self, right_table, left_key, right_key, inner)
    526                 right_hash[value] = []
    527 
--> 528             right_hash[value].append(self._rows[i])
    529 
    530         # Collect new rows

/home/katharine/.virtualenv/book/local/lib/python2.7/site-packages/agate/mapped_sequence.pyc in __getitem__(self, key)
     67         # Note: can't use isinstance because bool is a subclass of int
     68         elif type(key) is int:
---> 69             return self.values()[key]
     70         else:
     71             return self.dict()[key]

IndexError: tuple index out of range
```

I've attached the data files and the python to reproduce. Some altered versions of these tables will join but lose the column names. I'm also trying to get that into a reproducable state.

Excel files: https://github.com/jackiekazil/data-wrangling/blob/master/data/chp9/perceived_corruption_index.xls
https://github.com/jackiekazil/data-wrangling/blob/master/data/chp9/unicef_oct_2014.xls

Code: https://gist.github.com/kjam/b237fc5b503be3f7b438

Let me know if I'm doing something silly! Thanks!
-katharine

**Comment by onyxfish** [comment]
Filing this as a high priority bug (at least until I prove it isn't). This code did undergo fairly major refactoring, so it's very possible this is a new issue. (Though it should have been captured in unit tests.)

**Comment by kjam** [comment]
Aha! Also found way to reproduce the weird column thing. I am updating the gist. The 'Total (%)' column should be numbers (percentages). Instead it takes on the Country names. 

Updated gist at same place.

**Comment by onyxfish** [comment]
Looking into this now

**Comment by onyxfish** [comment]
Definitely a bug. In fact, probably at least two bugs. Working through them now.

**Comment by onyxfish** [comment]
Okay, I believe this is fixed on master. Can you please pull and confirm? (It looks fixed and my new tests pass, but I don't know your data well enough to be certain its doing what you expect.)

There were two issues, both related to joins which have multiple matches in the right-hand table. Sadly, I did not have a test covering this case.

**Comment by kjam** [comment]
yes, confirmed fixed! thank you so much :dancers:
