### ISSUE TITLE
pep 8 compatibility

### ISSUE THREAD

**Issue by staranjeet** [onyxfish/agate#342]
I ran a PEP8 test on your package and it listed many errors. I think a python package must comply with PEP8 guidelines. 
I can fix those issues and submit a PR.

**Comment by onyxfish** [comment]
Thanks for the interest, Taranjeet. However, I don't believe in being dogmatic about PEP8 compliance. I use a linter and do my best to apply the suggestions when they make sense. Sometimes they don't. If there are specific places where the PEP8 suggestions will improve the readability of the code I'm happy to have those in a pull request.

As [PEP20](https://www.python.org/dev/peps/pep-0020/) states: "practicality beats purity."
