### ISSUE TITLE
Exception when loading from a CSV which contains Chinese/Japanese

### ISSUE THREAD

**Issue by fangli** [onyxfish/agate#352]
Exception when loading from a CSV which contains Chinese/Japanese

>>> p = agate.Table.from_csv('/Users/felix/Desktop/details.csv', )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/felix/.virtualenvs/payments/lib/python2.7/site-packages/agate/table.py", line 235, in from_csv
    column_info = column_info.run(rows, column_names)
  File "/Users/felix/.virtualenvs/payments/lib/python2.7/site-packages/agate/data_types/__init__.py", line 80, in run
    if not column_type.test(row[i]):
  File "/Users/felix/.virtualenvs/payments/lib/python2.7/site-packages/agate/data_types/number.py", line 43, in test
    d = d.strip(symbol)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

details.csv content:

Gateway Type,Payment Method,Transaction Date,Canceled Time,Factory Seq No,Redeem Time,Price,MyCard Seq No,Transaction Status,Canceled,User Id,Product Name,Redeem Status,Success Date,Product Id,Card No,Factory Name,Feedback Seq No,User Price,Channel Name,Service Status
billing,台灣大哥大,2015/7/1 AM 12:12:50,,sssssssss,2015/7/1 AM 12:31:54,00,0105287,success,no,22222,00元,success,2015/7/1 AM 11:31:50,,,,,,,
billing,遠傳手機帳單,2015/7/1 AM 04:51:44,,sssssssss,2015/7/1 AM 04:52:56,00,70106039,success,no,22222,00元,success,2015/7/1 AM 02:52:54,,,,,,,

**Comment by onyxfish** [comment]
It looks like you're using Python 2. The Python 2 csv parser does not support unicode characters. However, if you run a `pip install csvkit`, agate will automatically use that parser instead, which does support  unicode.

I'm considering pulling the csvkit parser into agate core in the next version so you will be able to skip this step.

Closing this ticket--please reopen if you have more issues. Thanks!
