### ISSUE TITLE
Reorganize API for compute and aggregate

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/agate#378]
The single biggest piece of critical feedback I've gotten from 1.0 is that the aggregate/compute syntax is confusing. This has always been the part of the API I've been least satisfied with. The most commonly proposed alternative has been:

```
table.aggregate({
    'new_column': agate.Sum('old_column')
})
```

Or, to preserve order (without requiring OrderedDict):

```
table.aggregate([
   ( 'new_column', agate.Sum('old_column'))
])
```

In retrospect I'm inclined to agree both that this is more readable and that it fits the typical programming semantics (assignee to the left) more cleanly.

However, if we do this:

* We break the API in a really big way. (Though 1.1 will already to this with the new Table constructor.)
* Aggregations cease to be portable. (However, they become more like Computations.)
* We lose the ability to effectively cache aggregation results. (Unless the mechanism can be redesigned.)

With all these things in mind I'm inclined to change this and to do it ASAP so as few extensions and as little user code as possible will need to be rewritten.

@jeremyjbowers @rdmurphy @tylerfisher As some of the earliest adopters, I'd love to have your feedback on this idea before I make the changes.

**Comment by onyxfish** [comment]
Experimental work on this is now on the `new-api` branch.

**Comment by jeremyjbowers** [comment]
I'm good with this.

**Comment by onyxfish** [comment]
This is mostly working on the branch. In general I like it, but it creates one thing I really don't like. The syntax for executing an aggregation on a single column becomes:

```
total = Sum('column_name').run(table)
```

`run` could be renamed `apply` or something to be clearer, but it's still a pretty ugly syntax for a one-liner. My current thinking is to add a `Table.aggregate` method that is API-consistent with the existing `TableSet` method:

```
results = table.aggregate([
   Sum('column_name')
])
```

or:

```
total = table.aggregate(Sum('column_name'))
```

or, I suppose, for true consistency:

```
results = table.aggregate([
   ('total', Sum('column_name'))
])
```

In which case it would return an `OrderedDict`.

**Comment by onyxfish** [comment]
Actually, in that last case it return a `MappedSequence`.

**Comment by onyxfish** [comment]
As with so many things, actually doing this work makes it obvious that it's correct. Many of the documented examples get simpler and easier to understand this way. It also makes the Aggregation and Computation API's much more consistent and completes the migration of logic out of the Column data structure. Moreover, the logic of having the table (instead of the column) be the independent variable of an Aggregation actually aligns much better with the relationship between between Table and TableSet.

**Comment by onyxfish** [comment]
Side-benefit: Aggregations can now logically accept multiple column arguments (like Computations), which means something like Pearson Correlation can be implemented as an aggregation instead of a Table method.

https://github.com/onyxfish/agate-stats/blob/master/agatestats/table.py#L74

**Comment by onyxfish** [comment]
I believe this also means we could implement Regressions as single operators. Huzzah! Abstraction works.

**Comment by onyxfish** [comment]
Merged.

**Comment by rdmurphy** [comment]
I meant to respond to this much sooner but yeah +1 to all of it. ¯\_(ツ)_/¯ Changes make sense to me! I like that it uses tuples instead of `OrderedDict` too to maintain order. Reminds me of Django `choices`. Also glad this happened before any geo work started. :grin:

**Comment by onyxfish** [comment]
No worries, thanks for getting back to it! Once I had it documented it became pretty clear I had to make the change.
