### ISSUE TITLE
table.to_csv with a non-existing target directory gives an error

### ISSUE THREAD

**Issue by brentajones** [onyxfish/agate#392]
```
  File "prove.py", line 147, in compute_indexes
    computed_ordered.to_csv('output/computed.csv')
  File "/Users/brentjones/.virtualenvs/2015-11-05-we-live-here-suspensions/lib/python2.7/site-packages/agate/table.py", line 324, in to_csv
    f.close()
```

Tried to output to an "output" directory that I hadn't created, expecting the script to create the directory. Instead it gave me this error.

**Comment by onyxfish** [comment]
Not gonna call this a bug, because most libraries won't create the directory, but I aspire to be better than most libraries, so I'll call it a new feature to build. :+1: 

Thanks for reporting!

**Comment by onyxfish** [comment]
Note: whoever fixes this should fix it for `Table.to_json` as well.
