### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Table'

### ISSUE THREAD

**Issue by chrisalcantara** [onyxfish/agate#399]
Followed installation instructions on RTFD , tried running the example on my machine and ran into this error:
```
AttributeError: 'module' object has no attribute 'Table'
```

I'm running Python 2.7. The only module I imported into my example file was agate. Do I need additional dependencies?

**Comment by onyxfish** [comment]
Hi Chris, that's odd. Just to be clear, you followed the "user install" instructions and not the developer install instructions, right? And the example you were trying to run is the one from the front-page of the docs?

Any additional dependencies should have been installed automatically. Can you paste the full source you're running and the full traceback, please?

**Comment by chrisalcantara** [comment]
I did the user install and currently using the code from the front page of the docs.

```
import agate

purchases = agate.Table.from_csv('ks_1033_data.csv')

by_county = purchases.group_by('county')

totals = by_county.aggregate([
    ('county_cost', agate.Sum('total_cost'))
])

totals = totals.order_by('county_cost', reverse=True)
totals.limit(10).print_bars('county', 'county_cost', width=80)
```
Error message:
```
Traceback (most recent call last):
  File "/Users/calcantara/Desktop/prison_data/run.py", line 1, in <module>
    import agate
  File "/Users/calcantara/Desktop/prison_data/agate.py", line 4, in <module>
    purchases = agate.Table.from_csv('ks_1033_data.csv')
AttributeError: 'module' object has no attribute 'Table'
```

**Comment by onyxfish** [comment]
a\Ah ha! It looks like you named your script `agate.py` which is also the name of the library, so instead of importing agate it's importing your own code. Try renaming your script!

**Comment by chrisalcantara** [comment]
![doh-homer-simpson-doh](https://cloud.githubusercontent.com/assets/5307200/11103049/2aeb0f96-888e-11e5-8c97-4018a3013d83.jpg)

I completely missed that. It's working now. Thanks!

**Comment by onyxfish** [comment]
No problem, enjoy!

**Comment by AyushaSinha** [comment]
> Ah ha! It looks like you named your script `agate.py` which is also the name of the library, so instead of importing agate it's importing your own code. Try renaming your script!

Hi,

My script name is not same as lib, am getting this error:

Traceback (most recent call last):
  File "C:\Python\example.py", line 9, in <module>
    t = h.Table(table_dict)
AttributeError: module 'html' has no attribute 'Table'

Can you plz then tell me the solution.

this is my piece of code:
import json
import html
from html.entities import html5 as _html5
table = [{'Results': "Pass", 'Test Name' : "Test Case Name 1" , 'Time Taken' : "12:34:02"}]
[{'Results': "Fail", 'Test Name' : "Test Case Name 2" , 'Time Taken' : "03:00:02"}]
table_dict = json.dumps(table)
print(table_dict)
h = html
t = h.Table(table_dict)
f = open('C:\\Users\\Aayus\\Documents\\Ayushacodetest.html', 'w')
f.write(str(t))
f.close()
print(t)
