### ISSUE TITLE
Merged table doesn't use only the first table's column names

### ISSUE THREAD

**Issue by Kirkman** [onyxfish/agate#402]
The docs say when two tables are merged, "The first table’s column names will be the ones which are used."

I'm trying to build something using agate right now, and I'm finding this isn't true. When I merge two tables, it appears that each row keeps the column names it had in its source table.

So if I iterate over all rows in the merged table and print the row's keys, instead of all the keys being the same, I see something like this:

	('complaint_id', 'month_recorded', 'date', 'count', 'crime_code', 'district', 'crime_description', 'house_num', 'street', 'hood_code', 'x', 'y')
	('Complaint', 'CodedMonth', 'DateOccur', 'Count', 'Crime', 'District', 'Description', 'ILEADSAddress', 'ILEADSStreet', 'Neighborhood', 'XCoord', 'YCoord')
	...

This leads to key errors later when I try to use things like .where() or .select() on the merged table.

**Comment by onyxfish** [comment]
That sounds like a legit bug. I'll take a closer look.
