### ISSUE TITLE
Implement `TableSet.__str__`

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/agate#418]
To match `Table.__str__`

See also #416.

**Comment by onyxfish** [comment]
Can live without this for `1.2.0`

**Comment by nbedi** [comment]
@onyxfish is the structure of a TableSet a list of columns and column types as well or some sort of list of tables in the set?

**Comment by onyxfish** [comment]
@nbedi I have asked myself the same question and I don't really you have a good answer. Both seem reasonable and useful... thoughts?

**Comment by nbedi** [comment]
Maybe something like:

|---------------+---------------|
|  column_names | column_types  |
|---------------+---------------|
|  letter       | Text          |
|  number       | Number        |
|---------------+---------------|
|  table_names | row_count |
|---------------+---------------|
|  a       | 5          |
|  b       | 3        |
|---------------+---------------|

**Comment by onyxfish** [comment]
I think I'm probably leaning more toward just the latter, since it's always possible to get the column structure from the first table and it'll be less confusing to just print one thing.

In either case, we'll need to be careful about how large the "table of tables" can get, because a TableSet could theoretically have thousands of keys. I'd suggest we support a `max_rows` key like `print_table` does—and maybe even have that default to 20 or something.

**Comment by nbedi** [comment]
Sounds good, I'll try it out and submit a pull request

**Comment by onyxfish** [comment]
Thanks!
