### ISSUE TITLE
Need a way to select some columns from a table

### ISSUE THREAD

**Issue by TaurusOlson** [onyxfish/agate#422]
Sometimes a dataset has many columns and in some cases we actually need a table with a few of them. Selecting the columns we need to answer a particular problematic makes the work easier. 
The documentation doesn't talk about such a possibility. Is it implemented?

I think something like this would be intuitive and simple:

```
table.columns[(col1, col2, col3)]
```
If you think it's something agate needs, I can work on it.

**Comment by onyxfish** [comment]
[`Table.select`](http://agate.readthedocs.org/en/1.2.0/api/table.html#agate.table.Table.select) is what you want.

**Comment by TaurusOlson** [comment]
OK. Thanks. It's actually at the end of the documentation in the section `Emulate SQL`.

**Comment by onyxfish** [comment]
It's also mentioned in the [Selecting and filtering data](http://agate.readthedocs.org/en/1.2.0/tutorial.html#selecting-and-filtering-data) section of the tutorial, though there isn't an example.

**Comment by TaurusOlson** [comment]
Yes, I saw this section but read it fast, looked at the examples and just saw the one with `Table.where`.
