### ISSUE TITLE
Table.rename does not rename keys of Row items

### ISSUE THREAD

**Issue by ghing** [onyxfish/agate#423]
Looks like Table.rename() calls Table.fork(), which calls Table.__init__() with _is_fork=True which skips the code in this if block. Because of that, the _keys attribute of each Row instance retains the old values.

**Comment by onyxfish** [comment]
Hmmm, even when you pass `row_names`? That would be a rather large oversight on my part...

**Comment by ghing** [comment]
@onyxfish Yes, I believe so.  I'll try to write a test that breaks this when I have a second

**Comment by nbedi** [comment]
would be a rather large oversight on my part as well...

**Comment by ghing** [comment]
Sorry @onyxfish, @nbedi. Looks like column names in rows aren't renamed, in terms of dictionary access.  Here's the output from [this test](https://github.com/ghing/agate/blob/423-row_keys_not_renamed/tests/test_table.py#L1727):


```
nosetests tests/test_table.py
...........................................................................E.......................................................
======================================================================
ERROR: test_rename_column_names_renames_row_values (tests.test_table.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ghing/workspace/agate/tests/test_table.py", line 1733, in test_rename_column_names_renames_row_values
    self.assertEqual(row[key], row2[key2])
  File "/Users/ghing/workspace/agate/agate/mapped_sequence.py", line 69, in __getitem__
    return self.dict()[key]
KeyError: 'd'

----------------------------------------------------------------------
Ran 131 tests in 0.453s

FAILED (errors=1)
```

**Comment by ghing** [comment]
Looks like `Table.rename()` calls `Table.fork()`, which calls `Table.__init__()` with `_is_fork=True` which skips the code in [this `if` block](https://github.com/ghing/agate/blob/423-row_keys_not_renamed/agate/table.py#L135).  Because of that, the `_keys` attribute of each `Row` instance retains the old values.

**Comment by nbedi** [comment]
@ghing @onyxfish That does seem to be the issue. I added a pull request with a possible fix and @ghing's test for changing row keys. Let me know if that works or if you'd like it implemented differently. Sorry for the trouble.

**Comment by onyxfish** [comment]
Ah ha, this is an interesting bug. I overlooked it because that bit of state did not used to be part of the `Row`.

@nbedi Your fix looks good to me. Merged in!

**Comment by onyxfish** [comment]
I revised the test to use `assertColumnNames` and updated that testcase method to properly validate those keys. Should prevent errors like this in the future:

https://github.com/onyxfish/agate/commit/5997dea4365e1ee5f8ec8c839106542bc6144ed1
