### ISSUE TITLE
Check for column_types equivalence fails on types produced by TypeTester

### ISSUE THREAD

**Issue by nbedi** [onyxfish/agate#435]
My bad if this is intentional. It occurs in Table.merge and initializing TableSet. If one table with column_types generated by TypeTester is merged with another table, a merge error will be raised stating the types are not equal regardless of the second table's column types.

A simple way to see this is by removing the column_types parameter from init of table_a or table_b or both in the Table.merge test and printing the generated types. 

If it's not intentional, I think the fix is to check if column_types are instances of the same sub DataType class rather than checking if the lists are equal.

**Comment by onyxfish** [comment]
Hey, good catch. It is not intentional and your last suggestion sounds like the correct solution. This is an error I've made more than once, so I'm a bit familiar with that pattern!

**Comment by nbedi** [comment]
Thanks! Submitted a fix
