### ISSUE TITLE
Add option to truncate or wrap long values

### ISSUE THREAD

**Issue by jpmckinney** [onyxfish/agate#442]
csvkit issues:

* https://github.com/onyxfish/csvkit/issues/389

csvkit PRs:

* https://github.com/onyxfish/csvkit/pull/429
* https://github.com/onyxfish/csvkit/pull/482

**Comment by onyxfish** [comment]
Yep, this makes total sense. Should probably even default to something less than infinity. We should ellipsis the remainder to make it obvious it's been truncated.

**Comment by themiurgo** [comment]
Any hope to see wrapping rather than truncation?

**Comment by omar-rifai** [comment]
Reviving an old discussion but I think wrapping would still be a welcome feature.

**Comment by jugglinmike** [comment]
[At a maintainer's suggestion](https://github.com/wireservice/csvkit/issues/389#issuecomment-1371780396), I've opened gh-773 to discuss wrapping specifically.
