### ISSUE TITLE
Add csv.Sniffer (BLOCKING csvkit)

### ISSUE THREAD

**Issue by jpmckinney** [onyxfish/agate#444]
Otherwise, csvkit refactor is blocked.

**Comment by nbedi** [comment]
@jpmckinney added the implementation csvkit is using in table. let me know if that unblocks csvkit issues.

**Comment by jpmckinney** [comment]
Could you add a snifflimit argument to `from_csv` to set the length of the sample? The default can be zero (no sniffing, to maintain the current behavior). In order to sniff the entire file, I suppose `float("inf")` can be passed.

**Comment by nbedi** [comment]
Sure, we can still handle sniffing the entire file by passing `None` and on default it will be `0`

**Comment by jpmckinney** [comment]
K - `None` just seemed weird to me, but maybe it's better than `float('int')`, and I have no better suggestion.

**Comment by nbedi** [comment]
Look good? 7653310

**Comment by jpmckinney** [comment]
I might recommend taking the opportunity to rename to `sniff_limit` to be consistent with the other args. Otherwise looks good!

**Comment by nbedi** [comment]
Yup totally agree, thanks for pointing that out.
