### ISSUE TITLE
Add line_numbers support to csv.reader (BLOCKING csvkit)

### ISSUE THREAD

**Issue by jpmckinney** [onyxfish/agate#447]
See https://github.com/onyxfish/csvkit/pull/545

**Comment by nbedi** [comment]
@jpmckinney Let me know if this solves the issue: 96df0de

**Comment by jpmckinney** [comment]
I made a few comments on the commit.

**Comment by nbedi** [comment]
Had to step out for a bit, the recent commits should address all comments

**Comment by jpmckinney** [comment]
:+1:
