### ISSUE TITLE
Add option to disable type inference (BLOCKING csvkit)

### ISSUE THREAD

**Issue by jpmckinney** [onyxfish/agate#449]
I tried passing `column_types=agate.TypeTester(limit=0)`, but that doesn't seem to do it.

The desired behavior is for the column types to be `[agate.Text()] * len(columns)`. It's not possible to pass this list in `column_types`, as it requires CSVKit to know the number of columns without parsing the file (because it's just calling `from_csv` on a file).

Maybe a possible implementation is, if a single `DataType` is passed to Table via `column_types`, then that DataType is used for all columns.

**Comment by nbedi** [comment]
What did `column_types=agate.TypeTester(limit=0)` end up returning in your case?

**Comment by jpmckinney** [comment]
I don't have that code anymore - it just didn't turn off type inference (assuming I was doing things correctly). Would you have expected that to work?

**Comment by nbedi** [comment]
That's what I expected without looking into the code. Haven't done too much with TypeTester. Looking into it now.

**Comment by jpmckinney** [comment]
Aha, it tests _limit with just an `if`, but 0 is falsey in Python. Now I hit another bug, but I think it's almost there.

**Comment by nbedi** [comment]
Ohhh. Great catch.

**Comment by jpmckinney** [comment]
#450 for review.
