### ISSUE TITLE
Documentation is really buggy

### ISSUE THREAD

**Issue by milafrerichs** [onyxfish/agate#458]
Hey thanks for agate,

Love it. Use it in all my analysis projects.

But the documentation for 1.2 is really buggy, often links do not get resolved and lead to "This page does not exist yet." But when you reload sometimes it appears, at least, today. The other day I was not able to read the documentation at all.

E.g. this one had issues but then got resolved: http://agate.readthedocs.org/en/1.2.0/api/computations.html

Not sure what the problem and how to fix it. But wanted to let you know.

**Comment by onyxfish** [comment]
Yep, I've run into this too. I think when the 1.2 release got built RTFD choked on syncing to mirrors. I'm hoping when we roll 1.2.1 today that will fix things. If not I'll reach out to the RTFD folks and see if they can help.

Thanks for the ticket!

**Comment by onyxfish** [comment]
New release is out and this issue appears fixed. Closing out. Let me know if you see it again!
