### ISSUE TITLE
computations.Percent seems like it would be a good addition 

### ISSUE THREAD

**Issue by palewire** [onyxfish/agate#490]
Unless I'm missing it, right now you have to do something like this loop through a table and add a new calculated column with a percentage value.

```python
table = table.compute([
    ('percent', agate.Formula(agate.Number(), lambda row: row['count']/total))
])
```

To me something roughly like this might be nicer:

```python
total = 100
table = table.compute(('percent', agate.Percent('count', total))
```
Crazy? If you like the idea, I'd be happy to take a stab at contributing it.

**Comment by onyxfish** [comment]
Looks good to me! It would be cool if total defaulted to `None` and in that case it ran a `Sum` and used the total of the column.

**Comment by palewire** [comment]
Okay. I will take a run at it.
